verbose: true
base_link: torso_lift_link
models:
 - name: left_arm
   type: chain
   frame: l_wrist_roll_link
 - name: l_forearm_camera
   type: camera3d
   frame: l_forearm_cam_optical_frame
   topic: /l_forearm_cam/image_rect_color
free_frames:
 - name: tag_63
   x: true
   y: true
   z: true
   roll: true
   pitch: true
   yaw: true
 - name: l_forearm_cam_frame_joint
   x: true
   y: true
   z: true
   roll: true
   pitch: true
   yaw: true
free_frames_initial_values:
 - name: tag_63
   x: 0.35
   y: 0.0
   z: 0.0
   roll: -1.571
   pitch: -1.571
   yaw: 0.0
error_blocks:
 - name: hand_eye
   type: chain3d_to_chain3d
   model_a: l_forearm_camera
   model_b: left_arm
 - name: restrict_camera
   type: outrageous
   param: l_forearm_cam_frame_joint
   joint_scale: 0.0
   position_scale: 0.1
   rotation_scale: 0.1
