# TODO
chains:
  - name: left_arm
    joints:
     - l_shoulder_pan_joint
     - l_shoulder_lift_joint
     - l_upperarm_roll_joint
     - l_elbow_flex_joint
     - l_forearm_roll_joint
     - l_wrist_flex_joint
     - l_wrist_roll_joint
duration: 2.0
features:
  apriltags_finder:
    type: robot_calibration/AprilTagsFinder
    topic: /l_forearm_cam/image_rect_color
    camera_info_topic: /l_forearm_cam/camera_info
    camera_sensor_name: l_forearm_camera
    chain_sensor_name: left_arm
    tag_family:        'tag36h11' # options: tag36h11, tag36h10, tag25h9, tag25h7, tag16h5
    tag_border:        1          # default: 1
    tag_threads:       2          # default: 2
    tag_decimate:      1.0        # default: 1.0
    tag_blur:          0.0        # default: 0.0
    tag_refine_edges:  1          # default: 1
    tag_refine_decode: 0          # default: 0
    tag_refine_pose:   0          # default: 0
    tag_debug:         0          # default: 0
    publish_tf:        true       # default: false
    standalone_tags:
      [
      {id: 63, size: 0.13},
      ]
