verbose: true
base_link: torso_lift_link
models:
 - name: left_arm
   type: chain
   frame: l_wrist_roll_link
 - name: kinect2_camera
   type: camera3d
   frame: head_mount_kinect2_rgb_optical_frame
   topic: /kinect2/qhd/points
free_params:
 - l_shoulder_pan_joint
 - l_shoulder_lift_joint
 - l_upper_arm_roll_joint
 - l_elbow_flex_joint
 - l_forearm_roll_joint
 - l_wrist_flex_joint
 - l_wrist_roll_joint
 - head_pan_joint
 - head_tilt_joint
free_frames:
 - name: head_mount_kinect2_joint
   x: true
   y: true
   z: true
   roll: true
   pitch: true
   yaw: true
 - name: checkerboard
   x: true
   y: true
   z: true
   roll: true
   pitch: true
   yaw: true
free_frames_initial_values:
 - name: checkerboard
   x: 0.25
   y: 0.0
   z: -0.049
   roll: 1.57
   pitch: 0.0
   yaw: 0.0
error_blocks:
 - name: hand_eye
   type: chain3d_to_chain3d
   model_a: kinect2_camera
   model_b: left_arm
 - name: restrict_camera
   type: outrageous
   param: head_mount_kinect2_joint
   joint_scale: 0.0
   position_scale: 0.1
   rotation_scale: 0.1
