verbose: true
base_link: torso_lift_link
models:
 - name: right_arm
   type: chain
   frame: r_forearm_roll_link
 - name: azure_kinect
   type: camera3d
   frame: azure_kinect_rgb_camera_link_urdf
free_params:
 - r_shoulder_pan_joint
 - r_shoulder_lift_joint
 - r_upper_arm_roll_joint
 - r_elbow_flex_joint
 - r_forearm_roll_joint
# - head_pan_joint
# - head_tilt_joint
free_frames:
 - name: checkerboard
   x: true
   y: true
   z: true
   roll: true
   pitch: true
   yaw: true
# - name: azure_kinect_camera_base_joint
#   x: true
#   y: true
#   z: true
#   roll: false
#   pitch: true
#   yaw: false
free_frames_initial_values:
 - name: checkerboard
   x: 0.24005
   y: -0.0537838
   z: -0.0601343
   roll: 1.5707963267948966
   pitch: 0.0
   yaw: 3.141592653589793
error_blocks:
 - name: hand_eye
   type: chain3d_to_chain3d
   model_a: azure_kinect
   model_b: right_arm
# - name: restrict_camera
#   type: outrageous
#   param: azure_kinect_camera_base_joint
#   joint_scale: 0.0
#   position_scale: 0.1
#   rotation_scale: 0.1
