chains:
  - name: right_arm
    joints:
     - r_shoulder_pan_joint
     - r_shoulder_lift_joint
     - r_upperarm_roll_joint
     - r_elbow_flex_joint
     - r_forearm_roll_joint
  - name: head
    joints:
     - head_pan_joint
     - head_tilt_joint
duration: 2.0
features:
  checkerboard_finder:
    type: robot_calibration/CheckerboardFinder
    topic: /kinect2/qhd/points
    camera_info_topic: /kinect2/qhd/camera_info
    camera_sensor_name: kinect2_camera
    chain_sensor_name: right_arm
    points_x: 4
    points_y: 5
    size: 0.0245

