verbose: true
base_link: torso_lift_link
models:
 - name: right_arm
   type: chain
   frame: r_forearm_roll_link
 - name: kinect2_camera
   type: camera3d
   frame: head_mount_kinect2_rgb_optical_frame
   topic: /kinect2/qhd/image_color_rect
free_params:
 - r_shoulder_pan_joint
 - r_shoulder_lift_joint
 - r_upper_arm_roll_joint
 - r_elbow_flex_joint
 - r_forearm_roll_joint
free_frames:
 - name: tag_63
   x: true
   y: true
   z: true
   roll: true
   pitch: true
   yaw: true
free_frames_initial_values:
 - name: tag_63
   # transformation from tool frame
   x: 0.22
   y: 0.07
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: 0.0
error_blocks:
 - name: hand_eye
   type: chain3d_to_chain3d
   model_a: kinect2_camera
   model_b: right_arm
