###############################################
# PR2 calibration values
###############################################

## right arm (excluding Shadow Hand)
r_shoulder_pan_calib_ref: -0.74550427
r_shoulder_lift_calib_ref: 0.02804656
r_upper_arm_roll_calib_ref: -1.5587278
r_elbow_flex_calib_ref: -1.15635323
r_forearm_roll_calib_ref: 0.0015972

## left arm
l_shoulder_pan_calib_ref: 0.820049
l_shoulder_lift_calib_ref: -0.00294615
l_upper_arm_roll_calib_ref: 1.5892
l_elbow_flex_calib_ref: -1.28568
l_forearm_roll_calib_ref: 0.0299425
l_wrist_flex_calib_ref: -0.527021
l_wrist_roll_calib_ref: -1.50075

## head joints
head_pan_calib_ref: 0.0303234
head_tilt_calib_ref: 0.0110223

## laser
laser_calib_ref: 0.0

## torso joints
torso_calib_ref: 0.00475
