###############################################
# Pr2 calibration values
###############################################

## shoulder joints
r_shoulder_pan_calib_ref: -0.742357
r_shoulder_lift_calib_ref: -0.0205444
r_upper_arm_roll_calib_ref: -1.56191
l_shoulder_pan_calib_ref: 0.820049
l_shoulder_lift_calib_ref: -0.00294615
l_upper_arm_roll_calib_ref: 1.5892

## upper arm joints
r_forearm_roll_calib_ref: -0.0662134
l_forearm_roll_calib_ref: 0.0299425
r_elbow_flex_calib_ref: -1.07634
l_elbow_flex_calib_ref: -1.28568

## forearm joints
l_wrist_flex_calib_ref: -0.527021
l_wrist_roll_calib_ref: -1.50075

## head joints
head_pan_calib_ref: 0.0303234
head_tilt_calib_ref: 0.0110223

## laser
laser_calib_ref: 0.0

## torso joints
torso_calib_ref: 0.00475

## kinect2 joints
head_mount_kinect2_joint_x: -0.128057
head_mount_kinect2_joint_y: 0.00874907
head_mount_kinect2_joint_z: 0.0983058
head_mount_kinect2_joint_a: 0.00443006
head_mount_kinect2_joint_b: -0.00219447
head_mount_kinect2_joint_c: -0.00477909
