controller_list:
  - name: fake_base_controller
    joints:
      - world_joint
  - name: fake_left_arm_controller
    joints:
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
  - name: fake_left_arm_and_torso_controller
    joints:
      - torso_lift_joint
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
  - name: fake_right_arm_controller
    joints:
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_forearm_roll_joint
  - name: fake_right_arm_and_torso_controller
    joints:
      - torso_lift_joint
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_forearm_roll_joint
  - name: fake_arms_controller
    joints:
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_forearm_roll_joint
  - name: fake_head_controller
    joints:
      - head_pan_joint
      - head_tilt_joint
  - name: fake_torso_controller
    joints:
      - torso_lift_joint
  - name: fake_arms_and_torso_controller
    joints:
      - torso_lift_joint
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_forearm_roll_joint
  - name: fake_left_gripper_controller
    joints:
      - l_gripper_l_finger_joint
      - l_gripper_motor_slider_joint
      - l_gripper_motor_screw_joint
      - l_gripper_joint
  - name: fake_right_wrist_controller
    joints:
      - r_hand_WRJ2
      - r_hand_WRJ1
  - name: fake_right_first_finger_controller
    joints:
      - r_hand_FFJ4
      - r_hand_FFJ3
      - r_hand_FFJ2
      - r_hand_FFJ1
  - name: fake_right_middle_finger_controller
    joints:
      - r_hand_MFJ4
      - r_hand_MFJ3
      - r_hand_MFJ2
      - r_hand_MFJ1
  - name: fake_right_ring_finger_controller
    joints:
      - r_hand_RFJ4
      - r_hand_RFJ3
      - r_hand_RFJ2
      - r_hand_RFJ1
  - name: fake_right_little_finger_controller
    joints:
      - r_hand_LFJ5
      - r_hand_LFJ4
      - r_hand_LFJ3
      - r_hand_LFJ2
      - r_hand_LFJ1
  - name: fake_right_thumb_controller
    joints:
      - r_hand_THJ5
      - r_hand_THJ4
      - r_hand_THJ3
      - r_hand_THJ2
      - r_hand_THJ1
  - name: fake_right_fingers_controller
    joints:
      - r_hand_FFJ4
      - r_hand_FFJ3
      - r_hand_FFJ2
      - r_hand_FFJ1
      - r_hand_LFJ5
      - r_hand_LFJ4
      - r_hand_LFJ3
      - r_hand_LFJ2
      - r_hand_LFJ1
      - r_hand_MFJ4
      - r_hand_MFJ3
      - r_hand_MFJ2
      - r_hand_MFJ1
      - r_hand_RFJ4
      - r_hand_RFJ3
      - r_hand_RFJ2
      - r_hand_RFJ1
      - r_hand_THJ5
      - r_hand_THJ4
      - r_hand_THJ3
      - r_hand_THJ2
      - r_hand_THJ1
  - name: fake_right_hand_controller
    joints:
      - r_hand_WRJ2
      - r_hand_WRJ1
      - r_hand_FFJ4
      - r_hand_FFJ3
      - r_hand_FFJ2
      - r_hand_FFJ1
      - r_hand_LFJ5
      - r_hand_LFJ4
      - r_hand_LFJ3
      - r_hand_LFJ2
      - r_hand_LFJ1
      - r_hand_MFJ4
      - r_hand_MFJ3
      - r_hand_MFJ2
      - r_hand_MFJ1
      - r_hand_RFJ4
      - r_hand_RFJ3
      - r_hand_RFJ2
      - r_hand_RFJ1
      - r_hand_THJ5
      - r_hand_THJ4
      - r_hand_THJ3
      - r_hand_THJ2
      - r_hand_THJ1