# print messages to rosconsole as well
log_msgs: false

# add all limits to diagnostics
debug: false

# update rate for diagnostics
rate: 0.5

# can go that far outside limits without an error
limit_tolerance: 0.05
# getting that close to the limits (fraction of full range) will trigger a warning
warn_close_to_limit_fraction: 0.05

# per-joint overrides
joints:
  rh_FFJ1:
    warn_limit_margin: -1.0
  rh_MFJ1:
    warn_limit_margin: -1.0
  rh_RFJ1:
    warn_limit_margin: -1.0
  rh_LFJ1:
    warn_limit_margin: -1.0
  rh_THJ1:
    warn_limit_margin: -1.0
  rh_FFJ2:
    warn_limit_margin: -1.0
  rh_MFJ2:
    warn_limit_margin: -1.0
  rh_RFJ2:
    warn_limit_margin: -1.0
  rh_LFJ2:
    warn_limit_margin: -1.0
  rh_THJ4:
    warn_limit_margin: -1.0
  rh_LFJ5:
    warn_limit_margin: -1.0

  l_gripper_r_finger_tip_joint:
    warn_limit_margin: -1.0
  l_gripper_l_finger_tip_joint:
    warn_limit_margin: -1.0
  l_gripper_r_finger_joint:
    warn_limit_margin: -1.0
  l_gripper_l_finger_joint:
    warn_limit_margin: -1.0
  l_gripper_joint:
    warn_limit_margin: -1.0
  torso_lift_joint:
    warn_limit_margin: -1.0
  head_tilt_joint:
    warn_limit_margin: -1.0
  head_tilt_joint:
    limit_tolerance: 1.0
