# Initial pose
moveit_sim_hw_interface:
  joint_model_group: right_arm
  joint_model_group_pose: right_arm_to_side

# ros_control internal loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01

# controller to publish joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

hardware_interface:
  joints:
    - bl_caster_rotation_joint
    - bl_caster_l_wheel_joint
    - bl_caster_r_wheel_joint
    - br_caster_rotation_joint
    - br_caster_l_wheel_joint
    - br_caster_r_wheel_joint
    - fl_caster_rotation_joint
    - fl_caster_l_wheel_joint
    - fl_caster_r_wheel_joint
    - fr_caster_rotation_joint
    - fr_caster_l_wheel_joint
    - fr_caster_r_wheel_joint
    - torso_lift_joint
    - torso_lift_motor_screw_joint
    - head_pan_joint
    - head_tilt_joint
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_upper_arm_roll_joint
    - l_elbow_flex_joint
    - l_forearm_roll_joint
    - l_wrist_flex_joint
    - l_wrist_roll_joint
    - l_gripper_l_finger_joint
    - l_gripper_motor_slider_joint
    - l_gripper_motor_screw_joint
    - l_gripper_joint
    - laser_tilt_mount_joint
    - r_shoulder_pan_joint
    - r_shoulder_lift_joint
    - r_upper_arm_roll_joint
    - r_elbow_flex_joint
    - r_forearm_roll_joint
    - rh_WRJ2
    - rh_WRJ1
    - rh_FFJ4
    - rh_FFJ3
    - rh_FFJ2
    - rh_FFJ1
    - rh_LFJ5
    - rh_LFJ4
    - rh_LFJ3
    - rh_LFJ2
    - rh_LFJ1
    - rh_MFJ4
    - rh_MFJ3
    - rh_MFJ2
    - rh_MFJ1
    - rh_RFJ4
    - rh_RFJ3
    - rh_RFJ2
    - rh_RFJ1
    - rh_THJ5
    - rh_THJ4
    - rh_THJ3
    - rh_THJ2
    - rh_THJ1
  sim_control_mode: 0  # 0: position, 1: velocity
