sensors:
  - filtered_cloud_topic: filtered_cloud
    max_range: 5.0
    max_update_rate: 1.0
    padding_offset: 0.02
    padding_scale: 1.0
    point_cloud_topic: move_group/octomap_input
    point_subsample: 1
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater